import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/app/providers/ConvexProviderWithClerk";
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "@/components/navbar";

const mainFont = Fredoka({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "openbrain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} antialiased`}>
        <ClerkProvider>
          <ConvexClientProvider>
            <Navbar />
            {children}
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
