import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";

const mainFont = Fredoka({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "openBrain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} antialiased`}>{children}</body>
    </html>
  );
}
